### ISSUE TITLE
Connection refused when doing simple search

### ISSUE THREAD

**Issue by jaeyson** [typesense/laravel-scout-typesense-driver#28]
## Description

Hi! im getting networkexception, but im not sure if this has something to do with me setting up from docker or something else.

```Http\Client\Exception\NetworkException with message 'Failed to connect to localhost port 8108: Connection refused for "http://localhost:8108/collections/todo".'```

## Steps to reproduce

1. added in my existing docker-compose.yml
```yaml
...
  typsense:
    image: typesense/typesense:0.22.2
    container_name: typesense
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz
    volumes:
      - /tmp/typesense-server-data:/data
    ports:
      - "8108:8108"
    restart: "no"
    networks:
      laravel:
...
```

2. docker compose up -d, then `curl http://localhost:8108/health` which returned `{"ok":true}`

3. Followed the readme instructions section:
  - dependencies (guzzle7 adapter and laravel-scout-typesense-driver)
  - service provider
  - `artisan vendor:publish ...`
  - `config/scout.php`
  - `Searchable` trait as well as `TypesenseDocument` interface
  - setting `SCOUT_DRIVER` value to typesense
  - `php artisan scout:import App\\Models\\Todo`

## Expected Behavior

returning the searched results

## Actual Behavior

After the installation and syncing, I tried this inside `tinker`: `Todo::search('Test')->get();` then i get this

```
>>> Images::search('female')->get()
Http\Client\Exception\NetworkException with message 'Failed to connect to localhost port 8108: Connection refused for "http://localhost:8108/collections/todo".'
```

## Metadata

**Typsense Version**: 0.22.2

**OS**: macos 12.4

Laravel v8

**Comment by jaeyson** [comment]
Ah missed the small part `container_name: typesense`. It should be `typesense` instead of `localhost` for the hostname. closing this now

**Comment by dlogvin** [comment]
> Ah missed the small part `container_name: typesense`. It should be `typesense` instead of `localhost` for the hostname. closing this now

Hey, I'm experiencing the same exact issue. What do you mean with "It should be typesense instead of localhost for the hostname"?

**Comment by jaeyson** [comment]
@dlogvin im using `docker-compose.yml` an example:

```yaml
networks:
  appname:

services:
  typsense:
    image: typesense/typesense:0.23.0
    container_name: typesense
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz
    volumes:
      - /tmp/typesense-server-data:/data
    ports:
      - "8108:8108"
    restart: "no"
    networks:
      appname:
```

Here I'm using `typesense` (container name) as the hostname instead of localhost or 127.0.0.1

also in `scout.php`:

```php
    'typesense' => [
        'api_key'         => env('TYPESENSE_ADMIN_API_KEY', 'xyz'),
        'nodes'           => [
            [
                'host'     => env('TYPESENSE_NODE', 'typesense'),
                'port'     => env('TYPESENSE_PORT', '8108'),
                'path'     => '',
                'protocol' => env('TYPESENSE_PROTOCOL', 'http'),
            ],
        ],
        'nearest_node'    => [
            'host'     => env('TYPESENSE_NODE', 'typesense'),
            'port'     => env('TYPESENSE_PORT', '8108'),
            'path'     => '',
            'protocol' => env('TYPESENSE_PROTOCOL', 'http'),
        ],
        'connection_timeout_seconds'   => 2,
        'healthcheck_interval_seconds' => 30,    
        'num_retries'                  => 3,
        'retry_interval_seconds'       => 1,
    ],
```
